name: posts-test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - env:
        ACTIVE_PROFILE: test
      run: mvn clean test -f ./posts/pom.xml
